[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "socialmapper"
version = { file = "VERSION.txt" }
description = "A library for creating data-rich, spatial social service resource maps"
readme = "README.md"
authors = []
dependencies = [
    "beautifulsoup4",
    "cenpy",
    "folium",
    "fuzzywuzzy",
    "geopandas",
    "geopy",
    "matplotlib",
    "numpy",
    "osmnx",
    "overpy",
    "pandas",
    "python-dotenv",
    "python-Levenshtein",
    "requests",
    "shapely",
    "streamlit",
    "streamlit-folium",
    "stqdm",
    "tqdm",
    "contextily",
    "matplotlib-scalebar",
    "GitPython"
]

[project.optional-dependencies]
export = [
    "pyarrow>=14.0.0",
    "geoparquet>=0.1.0",
]
dev = [
    "black",
    "mypy",
    "pytest",
    "ruff",
    "twine",
    "build"
]

[project.urls]
"Homepage" = "https://github.com/mihiarc/socialmapper"
"Bug Tracker" = "https://github.com/mihiarc/socialmapper/issues"

[project.scripts]
socialmapper = "socialmapper.cli:main"

[tool.setuptools]
packages = ["socialmapper"]

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "B", "I"] 