"""CLI commands for managing feature flags."""

import typer
from typing import Optional
from rich.console import Console
from rich.table import Table
from rich.panel import Panel

from ..config.feature_flags import (
    get_feature_flags,
    UIMode,
    get_runtime_config,
    get_api_base_url,
    get_ui_base_url
)

console = Console()
app = typer.Typer(help="Manage SocialMapper feature flags")


@app.command()
def status():
    """Show current feature flag status."""
    flags = get_feature_flags()
    config = get_runtime_config()
    
    # Create status table
    table = Table(title="SocialMapper Feature Flags Status")
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")
    table.add_column("Description", style="dim")
    
    table.add_row("UI Mode", flags.ui_mode.value, "Current UI deployment mode")
    table.add_row("API Server", "✓" if flags.enable_api_server else "✗", "FastAPI backend server")
    table.add_row("Separated UI", "✓" if flags.enable_separated_ui else "✗", "Standalone Streamlit frontend")
    table.add_row("Legacy Imports", "✓" if flags.allow_legacy_imports else "✗", "Allow deprecated UI imports")
    table.add_row("Migration Notice", "✓" if flags.show_migration_notice else "✗", "Show migration information")
    table.add_row("Debug Mode", "✓" if flags.debug_mode else "✗", "Enable debug logging")
    
    console.print(table)
    
    # Show URLs if in separated mode
    if flags.ui_mode in [UIMode.SEPARATED, UIMode.HYBRID]:
        console.print("\n" + "="*50)
        console.print(f"🔗 API Server: {get_api_base_url()}")
        console.print(f"🖥️  Frontend UI: {get_ui_base_url()}")
        console.print("="*50)


@app.command()
def set_mode(
    mode: UIMode = typer.Argument(..., help="UI mode to set"),
    enable_api: bool = typer.Option(None, "--api/--no-api", help="Enable/disable API server"),
    enable_ui: bool = typer.Option(None, "--ui/--no-ui", help="Enable/disable separated UI")
):
    """Set the UI mode and related flags."""
    import os
    from pathlib import Path
    
    # Read current .env file or create new one
    env_file = Path(".env")
    env_vars = {}
    
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    
    # Update mode
    env_vars["SOCIALMAPPER_UI_MODE"] = mode.value
    
    # Set API and UI flags based on mode
    if mode == UIMode.SEPARATED:
        env_vars["SOCIALMAPPER_ENABLE_API_SERVER"] = "true"
        env_vars["SOCIALMAPPER_ENABLE_SEPARATED_UI"] = "true"
    elif mode == UIMode.HYBRID:
        env_vars["SOCIALMAPPER_ENABLE_API_SERVER"] = "true"
        env_vars["SOCIALMAPPER_ENABLE_SEPARATED_UI"] = "true"
    elif mode == UIMode.MONOLITHIC:
        env_vars["SOCIALMAPPER_ENABLE_API_SERVER"] = "false"
        env_vars["SOCIALMAPPER_ENABLE_SEPARATED_UI"] = "false"
    
    # Override with explicit flags if provided
    if enable_api is not None:
        env_vars["SOCIALMAPPER_ENABLE_API_SERVER"] = "true" if enable_api else "false"
    if enable_ui is not None:
        env_vars["SOCIALMAPPER_ENABLE_SEPARATED_UI"] = "true" if enable_ui else "false"
    
    # Write back to .env file
    with open(env_file, 'w') as f:
        f.write("# SocialMapper Feature Flags\n")
        f.write("# Generated by: socialmapper feature-flags set-mode\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    console.print(f"✅ Set UI mode to: {mode.value}")
    console.print(f"📝 Updated .env file")
    
    # Show next steps
    if mode in [UIMode.SEPARATED, UIMode.HYBRID]:
        panel = Panel.fit(
            f"[bold green]Next Steps:[/bold green]\n\n"
            f"1. Start backend API:\n"
            f"   cd socialmapper-api && ./setup-dev.sh\n\n"
            f"2. Start frontend UI:\n"
            f"   cd socialmapper-ui && ./setup-dev.sh\n\n"
            f"3. Access the separated UI at: {get_ui_base_url()}",
            title="Setup Instructions"
        )
        console.print(panel)


@app.command()
def validate():
    """Validate current feature flag configuration."""
    flags = get_feature_flags()
    issues = []
    
    # Check for configuration issues
    if flags.ui_mode == UIMode.SEPARATED:
        if not flags.enable_api_server:
            issues.append("API server should be enabled in separated mode")
        if not flags.enable_separated_ui:
            issues.append("Separated UI should be enabled in separated mode")
    
    if flags.ui_mode == UIMode.HYBRID:
        if not flags.enable_api_server:
            issues.append("API server should be enabled in hybrid mode")
        if not flags.enable_separated_ui:
            issues.append("Separated UI should be enabled in hybrid mode")
    
    if flags.ui_mode == UIMode.MONOLITHIC:
        if flags.enable_api_server:
            issues.append("API server is not needed in monolithic mode")
        if flags.enable_separated_ui:
            issues.append("Separated UI is not needed in monolithic mode")
    
    # Show results
    if issues:
        console.print("[red]⚠️  Configuration Issues Found:[/red]")
        for issue in issues:
            console.print(f"  • {issue}")
        console.print("\n[yellow]Run 'socialmapper feature-flags set-mode' to fix configuration[/yellow]")
    else:
        console.print("[green]✅ Configuration is valid[/green]")


if __name__ == "__main__":
    app()