// Mock import.meta.env for Jest
export const mockImportMetaEnv = {
  VITE_API_URL: 'http://localhost:8000',
  VITE_API_BASE_URL: 'http://localhost:8000',
  VITE_API_KEY: '',
  VITE_API_TIMEOUT: '30000',
  VITE_API_RETRY_ATTEMPTS: '3',
  VITE_API_RETRY_DELAY: '1000',
  VITE_ENABLE_CUSTOM_POIS: 'true',
  VITE_ENABLE_BATCH_ANALYSIS: 'true',
  VITE_ENABLE_ADVANCED_FILTERS: 'false',
  VITE_ENABLE_EXPERIMENTAL: 'false',
  VITE_MAP_CENTER_LAT: '40.7128',
  VITE_MAP_CENTER_LNG: '-74.0060',
  VITE_DEFAULT_MAP_LAT: '45.5152',
  VITE_DEFAULT_MAP_LNG: '-122.6784',
  VITE_DEFAULT_MAP_ZOOM: '12',
  VITE_MAP_DEFAULT_ZOOM: '10',
  VITE_MAP_MIN_ZOOM: '3',
  VITE_MAP_MAX_ZOOM: '18',
  VITE_MAP_TILE_PROVIDER: 'openstreetmap',
  VITE_MAP_TILE_URL: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  VITE_MAP_ATTRIBUTION: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  VITE_MAPBOX_TOKEN: '',
  VITE_UI_THEME: 'system',
  VITE_UI_DATE_FORMAT: 'MM/DD/YYYY',
  VITE_UI_NUMBER_FORMAT: 'en-US',
  VITE_UI_MAX_TOAST_MESSAGES: '5',
  VITE_UI_TOAST_DURATION: '5000',
  VITE_ANALYSIS_DEFAULT_TRAVEL_TIME: '15',
  VITE_ANALYSIS_MAX_TRAVEL_TIME: '60',
  VITE_ANALYSIS_DEFAULT_TRAVEL_MODE: 'walk',
  VITE_ANALYSIS_POLLING_INTERVAL: '2000',
  VITE_ANALYSIS_MAX_POLLING_ATTEMPTS: '300',
  VITE_POLL_INTERVAL: '2000',
  VITE_MAX_FILE_SIZE_MB: '10',
  VITE_ALLOWED_FILE_TYPES: '.csv,.xlsx,.xls,.json,.geojson',
  VITE_ANALYTICS_ENABLED: 'false',
  VITE_ANALYTICS_ID: '',
  VITE_DEV_ENABLE_DEVTOOLS: 'false',
  VITE_DEV_ENABLE_LOGGING: 'false',
  VITE_DEV_LOG_LEVEL: 'info',
  VITE_DEV_MOCK_API: 'false',
  DEV: false,
};

// Set up global mock
(global as any).mockImportMetaEnv = mockImportMetaEnv;